name: gh-pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /7th_christmas_card/